import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

import Navbar from "../components/Header/Navbar";
import Footer from "../components/Footer/Footer";
import Layout from "../components/Layout";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nike Ecommerce Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Layout>
          {/* HEADER SECTION */}
          <header>
            <Navbar />
          </header>
          {/* HEADER SECTION */}

          {children}

          {/* FOOTER */}
          <footer>
            <Footer />
          </footer>
          {/* FOOTER */}

          {/* TOASTER */}
          <Toaster position="bottom-right" toastOptions={{
            style:{
              background:'#000000',
              color:'#ffffff'
            }
          }} />
          {/* TOASTER */}
        </Layout>
      </body>
    </html>
  );
}
